### ISSUE TITLE
시작하기 전에 준비해두기

### ISSUE THREAD

**Issue by songkg7** [Learning-Is-Vital-In-Development/23-17-pair-programming-game#1]
## 시작하기 전에

- [x] README.md 작성
- [x] 프로젝트 기본 설정
- [x] GitHub Action: Test stage for Kotest and ktlint
- [x] [CodeCov](https://github.com/marketplace/actions/codecov)
- [x] PR size 
- [x] main branch read only
- [ ] PR 에 대한 빠른 피드백을 위해 Discord WebHook 적용에 대해 생각해보기
- [x] 자동화 테스트: #2 
- [x] CONTRIBUTION.md 작성: #4 
- [ ] Assign 방식 의견 묻고 정하기: random? or sequence

### ETC

- [Auto Assign](https://github.com/kentaro-m/auto-assign-action)

**Comment by dojinyou** [comment]
PR size LIVID ORG 에 추가해두었습니다!

**Comment by dojinyou** [comment]
CodeCov Action secrets 추가 완료하였습니다
